name: 'Terraform'
on:
  - push
jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Fmt
      run: terraform fmt -check
      continue-on-error: true

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color
      env:
        AWS_DEFAULT_REGION: ap-northeast-1
